export enum RoleEnum {
    ANALYSIS_OF_DATA_FROM_THE_CLIENT = 'ANALYSIS_OF_DATA_FROM_THE_CLIENT',
    DISTRIBUTION_OF_TASKS = 'DISTRIBUTION_OF_TASKS',
    DEPLOYING = 'DEPLOYING',
    DEVELOPMENT = 'DEVELOPMENT',
    TESTING = 'TESTING',
    RELEASE = 'RELEASE'
}